import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:intl/intl.dart';
import '../../models/invitation_model.dart';
import '../../providers/auth_provider.dart';
import '../../providers/invitation_provider.dart';
import '../../providers/contacts_provider.dart';
import '../../models/user_model.dart';
import '../../widgets/squircle_button.dart';
import '../../widgets/squircle_container.dart';

class CreateInvitationScreen extends StatefulWidget {
  final String bookingId;
  final String courtName;
  final String tennisCenterName;
  final DateTime date;
  final DateTime startTime;
  final DateTime endTime;
  
  const CreateInvitationScreen({
    super.key,
    required this.bookingId,
    required this.courtName,
    required this.tennisCenterName,
    required this.date,
    required this.startTime,
    required this.endTime,
  });

  @override
  State<CreateInvitationScreen> createState() => _CreateInvitationScreenState();
}

class _CreateInvitationScreenState extends State<CreateInvitationScreen> {
  final _messageController = TextEditingController();
  UserModel? _selectedContact;
  bool _isLoading = false;
  String? _error;
  
  @override
  void initState() {
    super.initState();
    
    // Load user contacts
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final authProvider = Provider.of<AuthProvider>(context, listen: false);
      if (authProvider.user != null) {
        final contactsProvider = Provider.of<ContactsProvider>(context, listen: false);
        contactsProvider.loadContacts(authProvider.user!.uid);
      }
    });
    
    // Set default message
    _messageController.text = 'Hey! Would you like to play tennis with me?';
  }
  
  @override
  void dispose() {
    _messageController.dispose();
    super.dispose();
  }
  
  Future<void> _sendInvitation() async {
    if (_selectedContact == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select a player to invite')),
      );
      return;
    }
    
    setState(() {
      _isLoading = true;
      _error = null;
    });
    
    try {
      final authProvider = Provider.of<AuthProvider>(context, listen: false);
      final invitationProvider = Provider.of<InvitationProvider>(context, listen: false);
      
      if (authProvider.user == null || authProvider.userModel == null) {
        throw Exception('User not authenticated');
      }
      
      // Create invitation
      final invitation = InvitationModel(
        id: '', // generated by the backend
        bookingId: widget.bookingId,
        creatorId: authProvider.user!.uid,
        creatorName: authProvider.userModel!.displayName,
        inviteeId: _selectedContact!.id,
        inviteeName: _selectedContact!.displayName,
        message: _messageController.text.trim(),
        status: InvitationStatus.pending,
        createdAt: DateTime.now(),
        expiresAt: DateTime.now().add(const Duration(days: 1)),
        priority: 1, // Setting a default priority
      );
      
      await invitationProvider.createInvitation(invitation);
      
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
        
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Invitation sent successfully')),
        );
        
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _isLoading = false;
          _error = 'Failed to send invitation: $e';
        });
        
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final dateFormat = DateFormat('EEEE, MMMM d, yyyy');
    final timeFormat = DateFormat('h:mm a');
    
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: const Text(
          'Invite a Player',
          style: TextStyle(fontWeight: FontWeight.bold),
        ),
        backgroundColor: Colors.white,
        elevation: 0,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Booking details card
            SquircleContainer(
              elevation: 2,
              color: Colors.white,
              cornerRadius: 12,
              cornerSmoothing: 0.6,
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      widget.courtName,
                      style: const TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    
                    const SizedBox(height: 4),
                    
                    Text(
                      widget.tennisCenterName,
                      style: TextStyle(
                        fontSize: 16,
                        color: Colors.grey[700],
                      ),
                    ),
                    
                    const SizedBox(height: 16),
                    
                    Row(
                      children: [
                        Icon(
                          Icons.calendar_today,
                          size: 16,
                          color: Colors.grey[600],
                        ),
                        const SizedBox(width: 8),
                        Text(
                          dateFormat.format(widget.date),
                          style: TextStyle(
                            color: Colors.grey[800],
                          ),
                        ),
                      ],
                    ),
                    
                    const SizedBox(height: 8),
                    
                    Row(
                      children: [
                        Icon(
                          Icons.access_time,
                          size: 16,
                          color: Colors.grey[600],
                        ),
                        const SizedBox(width: 8),
                        Text(
                          '${timeFormat.format(widget.startTime)} - ${timeFormat.format(widget.endTime)}',
                          style: TextStyle(
                            color: Colors.grey[800],
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
            
            const SizedBox(height: 24),
            
            // Select player section
            const Text(
              'Select Player',
              style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
              ),
            ),
            
            const SizedBox(height: 16),
            
            Consumer<ContactsProvider>(
              builder: (context, provider, child) {
                if (provider.isLoading) {
                  return const Center(
                    child: Padding(
                      padding: EdgeInsets.all(32.0),
                      child: CircularProgressIndicator(),
                    ),
                  );
                }
                
                if (provider.contacts.isEmpty) {
                  return SquircleContainer(
                    elevation: 2,
                    color: Colors.white,
                    cornerRadius: 12,
                    cornerSmoothing: 0.6,
                    child: Padding(
                      padding: const EdgeInsets.all(16),
                      child: Column(
                        children: [
                          Icon(
                            Icons.people_outline,
                            size: 48,
                            color: Colors.grey[400],
                          ),
                          const SizedBox(height: 16),
                          const Text(
                            'No contacts found',
                            style: TextStyle(
                              fontSize: 16,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                          const SizedBox(height: 8),
                          Text(
                            'Add players to your contacts to invite them',
                            style: TextStyle(
                              color: Colors.grey[600],
                            ),
                            textAlign: TextAlign.center,
                          ),
                          const SizedBox(height: 16),
                          SquircleButton(
                            label: 'Add Contacts',
                            onPressed: () {
                              // Navigate to add contacts screen
                            },
                            width: 150,
                            height: 50,
                          ),
                        ],
                      ),
                    ),
                  );
                }
                
                return SquircleContainer(
                  elevation: 2,
                  color: Colors.white,
                  cornerRadius: 12,
                  cornerSmoothing: 0.6,
                  child: ListView.separated(
                    shrinkWrap: true,
                    physics: const NeverScrollableScrollPhysics(),
                    itemCount: provider.contacts.length,
                    separatorBuilder: (context, index) => const Divider(height: 1),
                    itemBuilder: (context, index) {
                      final contact = provider.contacts[index];
                      final isSelected = _selectedContact?.id == contact.id;
                      
                      return ListTile(
                        leading: CircleAvatar(
                          backgroundColor: isSelected
                              ? Theme.of(context).colorScheme.primary
                              : Colors.grey[300],
                          backgroundImage: contact.profileImageUrl != null
                              ? NetworkImage(contact.profileImageUrl!)
                              : null,
                          child: contact.profileImageUrl != null
                              ? null
                              : Text(
                                  contact.displayName[0].toUpperCase(),
                                  style: TextStyle(
                                    color: isSelected ? Colors.white : Colors.black,
                                  ),
                                ),
                        ),
                        title: Text(
                          contact.displayName,
                          style: const TextStyle(
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        subtitle: Text(
                          'Level: ${contact.playerLevel.toString().split('.').last}',
                        ),
                        trailing: isSelected
                            ? Icon(
                                Icons.check_circle,
                                color: Theme.of(context).colorScheme.primary,
                              )
                            : null,
                        onTap: () {
                          setState(() {
                            _selectedContact = contact;
                          });
                        },
                        selected: isSelected,
                        selectedTileColor: Color.fromRGBO(
                          Theme.of(context).colorScheme.primary.r.toInt(),
                          Theme.of(context).colorScheme.primary.g.toInt(),
                          Theme.of(context).colorScheme.primary.b.toInt(),
                          0.1
                        ),
                      );
                    },
                  ),
                );
              },
            ),
            
            const SizedBox(height: 24),
            
            // Message section
            const Text(
              'Message',
              style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
              ),
            ),
            
            const SizedBox(height: 16),
            
            Card(
              elevation: 2,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12),
              ),
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: TextField(
                  controller: _messageController,
                  maxLines: 3,
                  decoration: const InputDecoration(
                    hintText: 'Add a personal message...',
                    border: InputBorder.none,
                  ),
                ),
              ),
            ),
            
            const SizedBox(height: 32),
            
            // Send invitation button
            SizedBox(
              width: double.infinity,
              child: SquircleButton(
                label: 'Send Invitation',
                onPressed: _isLoading ? () {} : () async {
                  await _sendInvitation();
                },
                width: double.infinity,
                height: 50,
              ),
            ),
            
            if (_error != null) ...[
              const SizedBox(height: 16),
              Text(
                _error!,
                style: const TextStyle(
                  color: Colors.red,
                ),
                textAlign: TextAlign.center,
              ),
            ],
            
            const SizedBox(height: 24),
          ],
        ),
      ),
    );
  }
}
